show_downloads: true
google_analytics:
theme: jekyll-theme-cayman-blog

title: "Ainchentmew2"
description: "Welcome to my website!"
baseurl: "/"
url: "https://ainchentmew2.github.io"

username: Ainchentmew2
user_title: Ainchentmew2
email: nvformella@gmail.com
github_username: Ainchentmew2

profile_picture: https://avatars.githubusercontent.com/u/17220280?s=400&u=7a220ef0586188f17e0605797c29d04b46635186&v=4
